spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:kraken_gcfa}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none


security:
  basic:
    enabled: false
server:
  port: ${SERVER_PORT:8081}

spring.http.multipart.max-file-size: ${UPLOAD_MAX_SIZE:10MB}
spring.http.multipart.max-request-size: ${UPLOAD_MAX_SIZE:10MB}