spring:
  datasource:
    url: jdbc:mysql://localhost/kraken_gcfa?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update


security:
  basic:
    enabled: false
server:
  port: 8081

spring.http.multipart.max-file-size: 10MB
spring.http.multipart.max-request-size: 10MB