INSERT IGNORE INTO role (id, name) VALUES (1, "ROLE_APPRENTICE");
INSERT IGNORE INTO role (id, name) VALUES (2, "ROLE_TUTOR");
INSERT IGNORE INTO role (id, name) VALUES (3, "ROLE_CONSULTANT");
INSERT IGNORE INTO role (id, name) VALUES (4, "ROLE_SUPER_ADMIN");